### ISSUE TITLE
Отправка пустого ответа в numeric и shortanswer

### ISSUE THREAD

**Issue by 0niel** [Ninja-Official/moodle-answers-script#4]
![image](https://user-images.githubusercontent.com/51058739/122645839-13bbc500-d125-11eb-9e51-d83ca5b7970f.png)
В shortanswer и numeric отсутствие ответа теперь считается за ответ. Наверное, стоит контролировать подобные ситуации на стороне сервера и клиента

**Comment by SyntOwl** [comment]
Займусь фиксом на стороне клиента.
Нужно будет почистить ответы в базе.
