### ISSUE TITLE
Изменения хэша изображения при изменении его размера

### ISSUE THREAD

**Issue by 0niel** [Ninja-Official/moodle-answers-script#7]
При изменении размера окна изменяются параметры изображения, и, следовательно, при обновлении страницы данный вопрос будет пересоздаваться в БД и счётчики ответов будут изменяться в разных полях в зависимости от размеров окна клиента. Это нужно исправить.
![image](https://user-images.githubusercontent.com/51058739/122651824-05c96c80-d144-11eb-9c63-68592b6feee8.png)

Кстати, быть может не хэшировать изображение, а заливать его "как есть", чтобы можно было потом смотреть изображения, залитые скриптом?

**Comment by 0niel** [comment]
Наверное, стоит использовать что-то типа этого https://stackoverflow.com/a/20285053/5065874 для получения base64 изображения по ссылке. Но нужно учесть, что иногда в src указывается не ссылка на изображение, а сам base64

**Comment by SyntOwl** [comment]
Можно отправлять на сервер base64 изображения, его можно легко конвертировать обратно в изображение [пример](https://codebeautify.org/base64-to-image-converter). Это в разы увеличит кол-во трафика для вопросов с изображениями.

**Comment by 0niel** [comment]
> Это в разы увеличит кол-во трафика для вопросов с изображениями.
Это не страшно. Давай отправлять base64 как он есть. В любом случае, мы 4к картинки на СДО вряд ли увидим и критических каких-то данных не придёт

**Comment by SyntOwl** [comment]
Нужно посмотреть серверную сторону.
При отправке полного изображения на сервер, сервер не дает ответ.

**Comment by 0niel** [comment]
эх... Я ошибся. Всё-таки данного размера изображения в БД сохраняется довольно долго. На локалке 1.5 секунд. Всё-таки придётся использовать хэш

**Comment by 0niel** [comment]
Могу предложить отправлять изображение в отдельную БД, в которой будет храниться сопоставления image data - image hash и не дожидаться ответа. Так будет лучше. Но пока что это не приоритетно, добавлю в issue потом
